[package]
name = "axum-actix"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.5"
axum = { version = "0.8.8" }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0" }
